
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IBISA.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Agreement
{

    public Agreement()
    {

        this.Transactions = new HashSet<Transaction>();

    }


    public int AgreementPrimaryId { get; set; }

    public Nullable<int> AgreementId { get; set; }

    public string AgreementNumber { get; set; }

    public string Location { get; set; }

    public string Zone { get; set; }

    public string Crop { get; set; }

    public string PlotId { get; set; }

    public Nullable<int> MaxPayout { get; set; }

    public Nullable<int> TargetContribution { get; set; }

    public string WalletAddress { get; set; }

    public string UserDisplayName { get; set; }



    public virtual ICollection<Transaction> Transactions { get; set; }

}

}
