

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IBISA.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Linq;


public partial class IBISAEntities : DbContext
{
    public IBISAEntities()
        : base("name=IBISAEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<TransactionType> TransactionTypes { get; set; }

    public DbSet<Agreement> Agreements { get; set; }

    public DbSet<Transaction> Transactions { get; set; }

    public DbSet<Iddir> Iddirs { get; set; }

    public DbSet<Option> Options { get; set; }

    public DbSet<Question> Questions { get; set; }

    public DbSet<User> Users { get; set; }

    public DbSet<WatcherRespons> WatcherResponses { get; set; }

    public DbSet<MachineAssessment> MachineAssessments { get; set; }


  
}

}

