
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IBISA.Data
{

using System;
    using System.Collections.Generic;
    
public partial class MachineAssessment
{

    public int MachineAssessmentId { get; set; }

    public Nullable<int> IddirId { get; set; }

    public string Zone { get; set; }

    public int Plot { get; set; }

    public int Anomaly { get; set; }

    public string AssessmentGroup { get; set; }

}

}
