
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IBISA.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Option
{

    public Option()
    {

        this.WatcherResponses = new HashSet<WatcherRespons>();

    }


    public int OptionId { get; set; }

    public string OptionName { get; set; }

    public int OptionValue { get; set; }

    public int QuestionId { get; set; }

    public byte DisplayOrder { get; set; }



    public virtual ICollection<WatcherRespons> WatcherResponses { get; set; }

}

}
