
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IBISA.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Question
{

    public int QuestionId { get; set; }

    public string Question1 { get; set; }

    public int IddirId { get; set; }

    public System.DateTime DueDate { get; set; }

    public System.DateTime CreatedDate { get; set; }



    public virtual Iddir Iddir { get; set; }

}

}
