
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IBISA.Data
{

using System;
    using System.Collections.Generic;
    
public partial class TransactionType
{

    public TransactionType()
    {

        this.Transactions = new HashSet<Transaction>();

    }


    public int TransactionTypeId { get; set; }

    public string TransactionType1 { get; set; }



    public virtual ICollection<Transaction> Transactions { get; set; }

}

}
