//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBISA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public int AgreementPrimaryId { get; set; }
        public string TransactionHash { get; set; }
        public Nullable<System.DateTime> DateOfAgreement { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> TransactionTypeId { get; set; }
    
        public virtual Agreement Agreement { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
