
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IBISA.Data
{

using System;
    using System.Collections.Generic;
    
public partial class WatcherRespons
{

    public int WatcherResponseId { get; set; }

    public int WatcherId { get; set; }

    public int QuestionId { get; set; }

    public int OptionId { get; set; }

    public System.DateTime CreatedDate { get; set; }



    public virtual Option Option { get; set; }

}

}
